# Generated by Django 4.0.2 on 2022-03-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Write your BIO here!', max_length=1500),
        ),
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.IntegerField(default=1000),
        ),
    ]
